name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ~/off-the-gully

    steps:
    - uses: actions/checkout@v3
    - name: Stop the current docker container
      run: docker stop off-the-gully
    - name: Rebuild the image
      run: docker build -t off-the-gully .
    - name: Run a container with the new image
      run: docker run -p 80:80 -d --name off-the-gully --rm off-the-gully
